/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 arm_chair__furniture.glb 
Author: maxsbond.work (https://sketchfab.com/maxsbond.work)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arm-chair-furniture-ec62634ebb5a41f491bbb9da04cd9dd1
Title: Arm chair / Furniture
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Arm_chair__furniture(props) {
  const { nodes, materials } = useGLTF('./glbFile/arm_chair__furniture.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.012}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_6.geometry} material={materials.Base} position={[0, 40.986, 0]} scale={43.314} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./glbFile/arm_chair__furniture.glb')
