/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 wooden_bed_free.glb 
Author: nijjar creative (https://sketchfab.com/nijjarcreative)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-bed-free-1c531f19ba9f4b7cadd1ea08eb8bfe2e
Title: Wooden Bed (Free)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Wooden_bed_free(props) {
  const { nodes, materials } = useGLTF('./glbFile/wooden_bed_free.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.348}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
          <group position={[-46.197, 77.021, -93.817]} rotation={[-1.573, 0, 0]} scale={[1.167, 1.368, 1]}>
            <mesh geometry={nodes['Box002_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[-0.057, -0.146, 79.188]} />
          </group>
          <group position={[52.819, 77.021, -93.817]} rotation={[-1.573, 0, 0]} scale={[1.167, 1.368, 1]}>
            <mesh geometry={nodes['Box003_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[-0.057, -0.146, 79.188]} />
          </group>
          <mesh geometry={nodes['bed_09_-_Default_0'].geometry} material={materials['09_-_Default']} position={[0, 0, -24.525]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.ChamferBox001_Male_default_0.geometry} material={materials.Male_default} position={[-0.039, 53.459, -26.173]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.bed_sheet_Male_default_0.geometry} material={materials.Male_default} position={[-0.134, 108.781, -24.284]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.04, 0.993, 1]} />
          <mesh geometry={nodes['Plane001_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[0, 106.602, 7.323]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./glbFile/wooden_bed_free.glb')
